version: "3.8"

services:
  frontend:
    image: ${ECR_REGISTRY}/tienda-perritos-frontend:latest
    container_name: tienda-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge